name:                laysRandom
version:             0.1.0.0
github:              "an-death/laysRandom"
license:             BSD3
author:              "Alexey Simuskov"
maintainer:          "saenarayoursorrow@gmail.com"
copyright:           "Copyright (c) 2019 Alexey Simuskov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ad-death/laysRandom#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- lens-aeson
- wreq
- random
- bytestring
- time
- http-client
- text

library:
  source-dirs: src

executables:
  laysRandom-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - laysRandom
    - wreq
    - random
    - lens
    - lens-aeson
    - bytestring
    - time
    - http-client
    - text

tests:
  laysRandom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - laysRandom
